### PR TITLE
restructure package loading

### PR DESCRIPTION
**Pull request by KristofferC**
@okvs Could you please try this instead and use:

```jl
if isdir(Pkg.dir("PimpMyREPL"))
    using PimpMyREPL

    atreplinit() do repl
        repl.interface = Base.REPL.setup_interface(repl; extra_repl_keymap = PimpMyREPL.Prompt.NEW_KEYBINDINGS)
    end
end
```

in your `.juliarc` file. I believe it should be a lot more stable with the loading.

To get this branch use: `Pkg.checkout("PimpMyREPL", "kc/restructure_loading")`

### CODE REVIEW

**Comment by KristofferC** [comment]
Also, you should be able to add your custom colorscheme anywhere after that section in your `.juliarc.jl`.

**Comment by KristofferC** [comment]
@Ismael-VC, would be grateful for any testing here too.

**Comment by okvs** [comment]
It works for me now :)

I did remove the `import` statements though, so I haven't tested that. But PimpMyREPL starts reliably, and I am able to add my custom colorscheme in `.juliarc`.

**Comment by KristofferC** [comment]
@okvs 

I did some updates here. It should be enough to only have `using PimpMyREPL` in the `.juliarc` file now. #20 should also be fixed. Could you please try it and see how things work.

**Comment by okvs** [comment]
A bare `using PimpMyREPL` in the `.juliarc` file now works fine for me. I can also add my own colorscheme with no problem.

#20 is also fixed for me.

**Comment by KristofferC** [comment]
Added a new way of printing colorschemes:

image

**Comment by KristofferC** [comment]
I have tested this on windows now and it seems to work well. Scream if something bad happens after this :)

**Pull request merged**
