### PR TITLE
add precompilation and highlighting for search

### PR DESCRIPTION
**Pull request by KristofferC**
- Precompilable
- Should highlight when pressing up and down

### CODE REVIEW

**Comment by Ismael-VC** [comment]
I can confirm it works on Windows 10 tested with Julia versions:

* 0.6.0-dev.62
* 0.5.0-rc3+0
* 0.4.6

This is awesome, thank you very much! :smile:

**Comment by Ismael-VC** [comment]
I have a broken pipe problem in v0.4.6, precompilation and highlighting for search works, but:

```julia
C:\Users\Ismael
λ julia
               _
   _       _ _(_)_     |  By greedy hackers for greedy hackers.
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _' |  |
  | | |_| | | | (_| |  |  Version 0.4.6 (2016-06-19 17:16 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE


julia> cd(Pkg.dir("PimpMyREPL"))

shell> git status
HEAD detached at origin/kc/precomp_and_searchhighlight
nothing to commit, working directory clean
```

**Comment by Ismael-VC** [comment]
I have noticed the following:

When using up arrow to recall a line from history, it is correctly colored, but if I simply type ENTER after evaluating the command, it looses the coloring.

But if I use up arrow **and** then right arrow or left arrow and finally hit ENTER, then and only then does the line remains colored.

I hope I made myself clear, if in doubt, please let me know, here is an image:

image

**Comment by KristofferC** [comment]
I understand. The REPL can be in many different modes and for that mode I have not "overloaded" the key to make the highlighting run. I will try to fix it.

**Comment by KristofferC** [comment]
I believe I fixed the issue with the non highlighting on a direct enter. I also added another colorscheme and some other stuff. Will look into the pipe error in win 0.4.6 now.

**Comment by KristofferC** [comment]
I can not repeat the broken pipe, Windows 10 with standard cmd:

image

**Comment by KristofferC** [comment]
@Ismael-VC can you try again with latest commit and see if it helped?

**Comment by KristofferC** [comment]
Since I now believe I handle the pipe thing correctly and I cant reproduce the problem on Windows I will merge this. Please ping me if there is still a problem.

**Comment by Ismael-VC** [comment]
Last update fixes everything, thank you very much.

**Pull request merged**
